### ISSUE TITLE
Fix avatar image

### ISSUE THREAD

**Issue by hugolpz** [oelali/oelali.github.io#1]
- [x] `assets/img/default/profile_pic.jpg` : replace.
- [x] `_data/conf/main.yml` > side_nav_profile_image_path: change path.

**Comment by oelali** [comment]
Salut @hugolpz. Bien reçu. Je m'en occupe dès que possible.

**Comment by oelali** [comment]
The necessary is done.

**Comment by hugolpz** [comment]
Ca a été rapide !
